image: maven:3.6.0-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    -  target/

stages:
  - test
  - package

test:
  stage: test
  script:
    - echo "=============== 开始编译  ==============="
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - mvn3

package:
  stage: package
  tags:
    - mvn3
  script:
    - echo "=============== 开始打包任务  ==============="
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true package